name: CI API FastAPI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  verificar-api:
    runs-on: ubuntu-latest
    
    # PARTE 4: A Matrix de Versões
    strategy:
      matrix:
        python-version: ["3.10", "3.11", "3.12"]

    steps:
    - uses: actions/checkout@v4

    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v5
      with:
        python-version: ${{ matrix.python-version }}

    - name: Instalar dependências
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Rodar Testes (Pytest)
      run: pytest

    # PARTE 5: Teste de Integração (O "CURL")
    - name: Subir a API e testar requisição (Integração)
      run: |
        # O '&' roda a API em background para não travar o Runner
        fastapi run main.py --port 8000 &
        # Dá 3 segundos para o servidor ligar
        sleep 3
        # O '-f' faz o CI falhar se a API retornar erro
        curl -f http://localhost:8000/
        curl -f http://localhost:8000/somar/10/20